edu_test/config/routes.rb
Rails.application.routes.draw do
  resources :question_types, only: :index
  resources :sections
  resources :themes, except: :index

  resources :scenarios do
    member do
      get :test_sessions
    end
  end

  resources :questions, except: :index do
    collection do
      get 'add_answer'
    end
  end

  resources :test_sessions, only: [:show, :index, :new, :create] do
    collection do
      post 'pass'
      post 'pass_part'
    end
  end

  resources :users, only: [:index] do
    collection do
      get :edit_current_user
      patch :update_current_user
      get :reset_current_user
    end
    member do
      get :test_sessions
    end
  end

  namespace :api do
    resources :users
  end

  get 'console', to: 'console#index'

  root 'application#index'
  get '*any', to: 'application#index'
end

edu_test/app/models/test_session.rb
# User test data
class TestSession < ApplicationRecord
  belongs_to :user
  belongs_to :scenario

  attr_accessor :page_size
  attr_accessor :group
  attr_accessor :before
  attr_accessor :after

  scope :full, -> { includes(:scenario).references(:scenario).order('scenarios.name, test_sessions.updated_at') }
  scope :search, ->(q) { full.where('scenarios.name ilike ? ', '%' + q + '%') if q.present? }

  delegate :questions, to: :scenario, prefix: true
  delegate :name,      to: :scenario, prefix: true

  after_create :set_questions_and_answers
  before_save :count_correct_answers!

  def questions
    set_questions_and_answers if data.blank?
    Question.find(data['questions']).sort { |x, y| data['questions'].index(x.id) <=> data['questions'].index(y.id) }
  end

  def expired?
    deadline < Time.now
  end

  # Order of AnswerVariant must be same in not expired session.
  def stud_answers(q)
    code_answers = data['code_answer'][q.id.to_s]
    return [nil] if q.open?
    ret_val = []
    if q.contact?
      avs = [AnswerVariant.find(code_answers[0]).sort_by{|x| code_answers[0].index(x.id)},
             AnswerVariant.find(code_answers[1]).sort_by{|x| code_answers[1].index(x.id)}]
      ret_val = avs.transpose
    else
      avs = q.answer_variants
      ret_val = avs.sort_by { |x| code_answers.index(x.id) }
    end
    ret_val
  end

  def convert_answer
    a_data = data['params']
    decode = {}
    data['questions'].each_with_index do |q, i|
      question = Question.find(q)
      decode[q.to_s] = nil
      unless a_data.blank?
        a_data_i = a_data[i.to_s]
        decode[q.to_s] = send("decode_#{question.code}", a_data_i, data['code_answer'][q.to_s]) if a_data_i.present? && (!%w(contact sortable).include?(question.code) || a_data_i.values.any?{|v| !v.blank?})
      end
    end
    data['answer'] = decode
    save!
  end

  def result
    r = {}
    questions.each do |q|
      s_qid = q.id.to_s
      next if data['answer'].blank?
      if data['answer'][s_qid].blank?
        r[q] = nil
      elsif q.str_open?
        r[q] = q.answer.body.include?(data['answer'][s_qid])
      elsif q.reg_open?
        r[q] = (data['answer'][s_qid] =~ eval(q.answer.body[0])) || false
      elsif q.multi_select?
        r[q] = data['answer'][s_qid].sort == q.answer.body.sort
      elsif q.sortable?
        r[q] = data['answer'][s_qid] == q.answer.body.map{|t| [t]}
      elsif q.contact?
        r[q] = data['answer'][s_qid] == q.answer.body.delete_if { |k, _| k.blank? }
        r[q] = nil if data['answer'][s_qid].blank?
      else
        r[q] = data['answer'][s_qid] == q.answer.body
      end
    end
    r
  end

  def correct_answers
    data['correct_answers']
  end

  private

  def count_correct_answers!
    cnt = 0
    result.each do |_, res|
      cnt += 1 if res
    end
    self.data = self.data.merge({'correct_answers' => cnt})
    cnt
  end

  def decode_sortable(a_data, q_data)
    decode_q = Array.new(a_data.size){|_| []}
    a_data.each do |key, val|
      decode_q[val.to_i - 1] << q_data[key.to_i]
    end
    decode_q
  end

  def decode_str_open(a_data, _)
    a_data
  end

  def decode_reg_open(a_data, _)
    a_data
  end

  def decode_one_select(a_data, q_data)
    decode_q = []
    a_data.each { |index| decode_q << q_data[index.to_i] }
    decode_q
  end

  alias decode_multi_select decode_one_select

  def decode_contact(a_data, q_data)
    decode_q = {}
    a_data.each do |a_num, c_num|
      a = q_data[0][a_num.to_i].to_s
      decode_q[a] ||= []
      decode_q[a] << (c_num.blank? ? nil : q_data[1][c_num.to_i - 1])
      decode_q[a].compact!
    end
    decode_q.each  do |k, v|
      decode_q[k] = v[0] if v.size == 1
      decode_q[k] = nil if v.size == 0
    end
    decode_q
  end

  def set_questions_and_answers
    self.data ||= {}
    self.data['questions'] = scenario.questions.map(&:id)
    self.data['code_answer'] = {}
    self.data['questions'].each do |q|
      self.data['code_answer'][q.to_s] = Question.find(q).stud_answers
    end
    save!
  end

end

edu_test/app/controllers/test_sessions_controller.rb
require 'edu_support'
require 'students'
# Controller contains operations with user test sessions
class TestSessionsController < ApplicationController
  DELTA = 10

  layout 'student', except: [:index, :show, :pass]

  before_action :set_test_session, only: [:pass, :pass_part]
  before_action :validate_user_test_session, only: [:pass, :pass_part, :new]

  # OK
  def index
    if @current_user.only_student?
      @test_sessions = TestSession.includes(:user, :scenario).where(user_id: @current_user.id).order("updated_at DESC").page(params[:page]).per(25)
      render :stud_index and return
    end
    page_size = params[:page_size] || 25
    cond = []

    cond << "(scenario_id in (#{params['scenario'].map{|q| q.to_i}.join(',')}))" unless params['scenario'].blank?

    unless params['user'].blank?
      user = User.where(login: params['user']).first
      id = user.nil? ? 0 : user.id
      cond << "(user_id = #{id})"
    end

    unless params[:group].blank?
      begin
        #raise EduSupport.group_info(URI::encode(params[:group]), StudyYear.current_semester)['students'].inspect
        ids = params[:group].upcase.split.map do |g|
          EduSupport.group_info(URI::encode(g), StudyYear.current_semester)['students'].map{|q| User.where(login: q['login']).first.try(:id)}.compact
        end.flatten
      rescue
        ids = []
      end
      ids = [0] if ids.size == 0
      cond << "(user_id in (#{ids.join(',')}))"
    end

    unless params[:before].blank?
      begin
        t = Time.parse(params[:before])
        cond << "(updated_at <= '#{t.utc}')"
      rescue
      end
    end

    unless params[:after].blank?
      begin
        t = Time.parse(params[:after])
        cond << "(updated_at >= '#{t.utc}')"
      rescue
      end
    end

    cond = cond.join(' and ')
    @test_sessions = TestSession.includes(:user, :scenario).where(cond).order("updated_at DESC").page(params[:page]).per(params[:page_size])
    @scenarios = Scenario.all.order(updated_at: :desc, name: :asc)
    @groups = Group.all
  end

  # Попытка начать тестирование (корректная или нет)
  def new
    begin
      scenario = Scenario.find(params[:scenario_id])
      unless scenario.version.nil?
        redirect_to :scenario_id => Scenario.where(name: scenario.name, version: nil).first.id and return
      end
    rescue
      redirect_to :scenario_id => Scenario.first.id and return
    end

    unless @current_user.tutor?
      unless scenario.allow?(@current_user)
        render_error('Тестирование запрещено') and return
      end
    end

    @test_session = TestSession.where(id: session[:test_session]).first ||
                    TestSession.where(user_id: @current_user.id, scenario_id: scenario.id).last
    if @test_session.blank? || @test_session.expired?
      @test_session = TestSession.create!(user: @current_user, scenario_id: scenario.id, deadline: Time.now.advance(minutes: scenario.duration))
    elsif @test_session.scenario_id != scenario.id
      redirect_to :scenario_id => @test_session.scenario_id and return
    end
    session[:test_session] = @test_session.id
  end

  # Завершение тестирования (корректного или нет)
  def pass
    if @test_session.blank?
      render_error "Тестирование уже было завершено" and return
    end
    begin
      if Time.now < @test_session.deadline.advance(seconds: DELTA)
        @test_session.deadline = Time.now
        @test_session.save # Сохраняем, так как следующая строка может
                           # и не выполниться (в случае "подлога")
        # Действия ниже могут оказаться относящимися к иной сессии
        # (если человек совершает некорректные операции)
        # В этом случае, скорее всего, конвертация не пройдёт!
        @test_session.data['params'] = params[:answer]
        @test_session.convert_answer
      end
    rescue
    end
    session.delete(:test_session)
  end

  # Переход к иному вопросу (в корректном тестировании или нет)
  def pass_part
    begin
      if Time.now < @test_session.deadline.advance(seconds: DELTA)
        @test_session.data['params'] = params[:answer]
        @test_session.convert_answer
      end
      ids = []
      unless @test_session.data['answer'].nil?
        @test_session.data['questions'].each_with_index do |q, i|
          ids << i.to_s if @test_session.data['answer'][q.to_s]
        end
      end
      render json: { success: true, data: { tabs: ids } }
    rescue
      render json: { error: true }
    end
  end

  # Показ результатов при наличии прав и корректности запроса
  def show
    begin
      @test_session = TestSession.find(params[:id])
    rescue
      redirect_to root_path
    end
    validate_user_test_session unless @current_user.tutor? || @current_user.admin?
  end

  private

  def set_test_session
    @test_session = TestSession.where(id: session[:test_session]).first
  end

  def validate_user_test_session
    if @test_session && @current_user != @test_session.user
      redirect_to root_path
    end
  end
end

edu_test/app/helpers/test_sessions_helper.rb
module TestSessionsHelper
  def result_class(r)
    return 'text-success fa fa-check' if r
    return 'text-warning fa fa-question' if r.nil?
    'text-danger fa fa-remove'
  end

  def result_text(r)
    return 'сдано' if r
    return 'нет ответа' if r.nil?
    'не сдано'
  end

  def active_class(index, options = {})
    res = []
    res.push 'active' if index == 0
    if options[:include_nav]
       if index == 0
         res.push 'first-page-link'
       elsif index + 1 == options[:size]
         res.push 'last-page-link'
       end
    end
    res
  end

  def duration_session(ts)
    (ts.deadline - Time.now()).to_i
  end

end

edu_test/app/views/test_sessions/_test_session_row.html.haml
.list-group-item
  .row
    .col-md-9
      = link_to (local_assigns[:display] ? test_session.user.full_name : "#{test_session.user.short_name} — #{test_session.scenario.full_name}"), test_session_path(test_session)
    .col-md-2
      = l test_session.updated_at
    .col-md-1
      = test_session.correct_answers
      =?/
      = test_session.data['questions'].count

edu_test/app/views/test_sessions/index.html.haml
.container-fluid
  .my-3
    = link_to 'Перейти на «Подспорье»', 'https://edu-support.mephi.ru', class: 'btn btn-info my-4'
    = link_to 'Перейти на корпоративный портал', 'https://home.mephi.ru', class: 'btn btn-info my-4'
    = form_tag test_sessions_path, method: 'get', class: 'mx-4' do
      .row
        .col-md-12
          = select_tag :scenario, options_from_collection_for_select(@scenarios, :id, :full_name, params[:scenario]),  multiple: true, class: 'form-control'
      .row.mt-2
        .col-md-3
          = text_field_tag :group, params.permit![:group], placeholder: 'Разделённые пробелом группы', class: 'form-control'
        .col-md-1
          = text_field_tag :user, params.permit![:user], placeholder: 'Логин', class: 'form-control'
        .col-md-2
          = text_field_tag :page_size, params[:page_size], placeholder: 'Размер страницы', class: 'form-control'
        .col-md-2
          = text_field_tag :before, params[:before], placeholder: 'Не позже', class: 'form-control'
        .col-md-2
          = text_field_tag :after, params[:after], placeholder: 'Не ранее', class: 'form-control'
        .col-md-2
          = button_tag type: 'submit', class: 'btn btn-primary' do
            =fa_icon 'search'
            Поиск
    %h2.mt-4 Найденные тестирования
    %nav.pagination.justify-content-center
      = paginate @test_sessions
    .list-group
      - @test_sessions.each do |ts|
        = render 'test_sessions/test_session_row', test_session: ts
    %nav.mt-2.pagination.justify-content-center
      = paginate @test_sessions

edu_test/app/views/test_sessions/new.html.haml
= content_for :navbar do
  #clock{ data: { duration: duration_session(@test_session) } }

.container-fluid
  .my-3
    = form_tag pass_test_sessions_path, class: 'ui form test-form' do
      .actions.text-center
        = submit_tag(t('helpers.buttons.test'), data: {confirm: 'Вы не сможете вернуться к этому тестированию позже. Вы уверены, что хотите завершить его?'}, class: 'btn btn-secondary')
      .clearfix
      .my-4.d-flex.justify-content-between.align-items-end
        %a.page-link.left-question.invisible{href: ?#} Предыдущий вопрос
        .pagination.nav.nav-tabs.border-0.questions-list
          .page-item.nav-item.float-left
          - @test_session.questions.each_with_index do |_, i|
            .page-item.nav-item
              %a.page-link{ href: "#tab#{i}", class: "#{active_class(i, include_nav: true, size: @test_session.questions.size).join(' ')} #{@test_session.data['answer'].nil? || @test_session.data['answer'][@test_session.data['questions'][i].to_s].nil? ? '' : 'processed'}", data: { toggle: 'tab'}}
                = i + 1
        %a.page-link.right-question{href: ?#} Следующий вопрос
      .tab-content
        - @test_session.questions.each_with_index do |q, i|
          .tab-pane{ class: active_class(i), id: "tab#{i}", role: "tabpanel"}
            .card.d-flex.align-items-stretch.my-4
              .card-header
                %h4
                  = "Задание #{i+1}"
              .card-body
                .card-title.test-question
                  = preserve(markdown(q.body))
                - answers = @test_session.stud_answers(q)
                - answers.each_with_index do |a_var, j|
                  = render "answers/test_session/#{q.code}", question: q, q_num: [i], answer: a_var, a_num: j, answers: answers, s_params: @test_session.data['params']

edu_test/app/views/test_sessions/pass.html.haml
.container
  .my-3
    .card
      .card-header
        %h2
          = l(@test_session.updated_at)
          = @test_session.scenario_name

      .card-body
        - @test_session.result.each do |q, result|
          .item
            %i.icon{ class: result_class(result) }
            = q.theme_name

    = link_to 'Подробнее о результатах завершившегося тестирования', @test_session, class: 'btn btn-info my-4'

    = link_to 'Перейти на «Подспорье»', 'https://edu-support.mephi.ru', class: 'btn btn-info my-4'

    = link_to 'Перейти на корпоративный портал', 'https://home.mephi.ru', class: 'btn btn-info my-4'

edu_test/app/views/test_sessions/show.html.haml
.container-fluid
  .my-3
    %h3
      = @test_session.user.full_name
      = link_to 'Перейти на «Подспорье»', 'https://edu-support.mephi.ru', class: 'btn btn-info my-4'
      = link_to 'Перейти на корпоративный портал', 'https://home.mephi.ru', class: 'btn btn-info my-4'
    %h4
      = l(@test_session.updated_at)
      = @test_session.scenario_name
  .accordion#test-session-data{role: 'tablist'}
    - @test_session.result.each_with_index do |r, i|
      .card.mb-2
        .card-header.border{id: "heading#{i}"}
          %i{ class: result_class(r[1]) }
          %a.text-dark{data: {toggle: 'collapse'}, href: "#collapse#{i}", aria: {expanded: false}}= r[0].theme_name
        .collapse.multi-collapse.show{id: "collapse#{i}", aria: {labelledby: "heading#{i}" }}
          .card-body
            = preserve(markdown(r[0].body))
            .row
              .col-md-6
                .text-bold Правильный ответ
                = render "answers/show/#{r[0].code}", answer: r[0].code == 'reg_open' ? "/#{r[0].answer.body[0]}/"[1..-2] : r[0].answer.body, answer_variants: r[0].r_answers
              .col-md-6.border-0
                .text-bold Ответ тестируемого
                = render "answers/show/#{r[0].code}", answer: @test_session.data['answer'][r[0].id.to_s], answer_variants: r[0].r_answers



  .my-3
    %h3
      = link_to 'Перейти на «Подспорье»', 'https://edu-support.mephi.ru', class: 'btn btn-info my-4'
      = link_to 'Перейти на корпоративный портал', 'https://home.mephi.ru', class: 'btn btn-info my-4'

edu_test/app/views/test_sessions/stud_index.html.haml
.container-fluid
  = link_to 'Перейти на «Подспорье»', 'https://edu-support.mephi.ru', class: 'btn btn-info my-4'
  = link_to 'Перейти на корпоративный портал', 'https://home.mephi.ru', class: 'btn btn-info my-4'
  %h2.mt-4 Найденные тестирования
  %nav.pagination.justify-content-center
    = paginate @test_sessions
  .list-group
    - @test_sessions.each do |ts|
      = render 'test_sessions/test_session_row', test_session: ts
  %nav.mt-2.pagination.justify-content-center
    = paginate @test_sessions