edu_test/config/routes.rb
Rails.application.routes.draw do
  resources :question_types, only: :index
  resources :sections
  resources :themes, except: :index

  resources :scenarios do
    member do
      get :test_sessions
    end
  end

  resources :questions, except: :index do
    collection do
      get 'add_answer'
    end
  end

  resources :test_sessions, only: [:show, :index, :new, :create] do
    collection do
      post 'pass'
      post 'pass_part'
    end
  end

  resources :users, only: [:index] do
    collection do
      get :edit_current_user
      patch :update_current_user
      get :reset_current_user
    end
    member do
      get :test_sessions
    end
  end

  namespace :api do
    resources :users
  end

  get 'console', to: 'console#index'

  root 'application#index'
  get '*any', to: 'application#index'
end

edu_test/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :theme
  belongs_to :question_type

  has_one :answer, dependent: :destroy
  has_many :answer_variants, dependent: :destroy

  accepts_nested_attributes_for :answer
  accepts_nested_attributes_for :answer_variants, reject_if: :blank?

  delegate :section, to: :theme, prefix: false
  delegate :section_name, to: :theme, prefix: false
  delegate :name, to: :theme, prefix: true
  delegate :need_variants, to: :question_type, allow_nil: true, prefix: false

  validates :body, :question_type_id, :code, presence: true
  # validates_presence_of :answer_variants, if: :need_variants

  before_destroy :can_destroy?
  # TODO: no destroy when has scenarios
  def can_destroy?
    true
  end

  def self.can_destroy?
    true
  end

  def r_answers
    return answer.body if open?
    answer_variants
  end

  def stud_answers
    return [nil] if open?
    if contact?
      # side one always first
      avs1 = answer_variants.group_by(&:side)
      [avs1['1'], avs1['2']].map(&:shuffle).map{ |x| x.map(&:id) }
    else
      answer_variants.shuffle.map(&:id)
    end
  end

  def open?
    %w(str_open reg_open).include?(code)
  end

  def str_open?
    code == 'str_open'
  end

  def reg_open?
    code == 'reg_open'
  end

  def multi_select?
    code == 'multi_select'
  end

  def contact?
    code == 'contact'
  end

  def sortable?
    code == 'sortable'
  end
end

edu_test/app/models/question_type.rb
class QuestionType < ApplicationRecord
  has_many :questions
  CODES = %w(str_open reg_open one_select multi_select sortable contact).freeze

  validates :code, uniqueness: true

  CODES.each do |c_name|
    scope c_name.to_sym, -> { where(code: c_name).first }
  end
end

edu_test/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :admin_user, except: [:index, :show]
  before_action :tutor_user, only: [:index, :show]
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new(theme_id: params[:theme_id])
    @q_types = QuestionType.all
  end

  # GET /questions/1/edit
  def edit
    @q_types = QuestionType.all
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_answer
    render partial: "answers/#{params[:question_type]}"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.require(:question).permit(:user_id, :theme_id, :body, :question_type_id, answer_attributes: [:text])
  end

end

edu_test/app/helpers/questions_helper.rb
module QuestionsHelper
end

edu_test/app/views/questions/_form.html.haml
= bootstrap_form_for @question, html: { class: 'question-form' } do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  = f.association :theme, disabled: true
  = f.input :theme_id, as: :hidden
  = f.association :question_type, collection: QuestionType.all.map { |q_t| [q_t.name, q_t.id, {data: {type: q_t.code}}] }
  = f.input :body, as: :text
  = f.input :hidden, as: :checkbox, wrapper: :slider

  .ui.divider
  .answer
  .answer-variants
  .ui.buttons
    -# = f.button :submit, t('simple_form.submit')
    .ui.button.primary#add_answer{ data: { url: add_answer_questions_path } } Перейти в к ответам

edu_test/app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', @question
\|
= link_to 'Back', questions_path

edu_test/app/views/questions/index.html.haml
%h1 Listing questions

%table
  %thead
    %tr
      %th User
      %th Theme
      %th Body
      %th Question type
      %th
      %th
      %th

  %tbody
    - @questions.each do |question|
      %tr
        %td= question.user
        %td= question.theme
        %td= question.body
        %td= question.question_type
        %td= link_to 'Show', question
        %td= link_to 'Edit', edit_question_path(question)
        %td= link_to 'Destroy', question, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Question', new_question_path

edu_test/app/views/questions/new.html.haml
- content_for :breadcrumb do
  = sections_breadcrumb
  .section= link_to @question.section_name, @question.section
  = divider_tag
  .section.active= link_to @question.theme_name, @question.theme
  = divider_tag
  .section.active= title(:questions, :new)

.ui.segment
  %h2.ui.header.dividing=title(:themes, :new)
  = render 'form'

edu_test/app/views/questions/show.html.haml
- content_for :breadcrumb do
  %span.breadcrumb-item= sections_breadcrumb
  %span.breadcrumb-item= link_to @question.theme.section_name, @question.theme.section
  %span.breadcrumb-item= link_to @question.theme_name, @question.theme
  %span.breadcrumb-item.active=  @question.id


-#.ui.buttons.floated.right.floated
  = link_to edit_question_path(@question), class: 'button orange ui icon right floated' do
    = semantic_icon 'pencil'
    = t('helpers.buttons.edit')
  = link_to question_path(@question), class: 'button red ui icon right floated', data: {method: :delete, confirm: t('helpers.sure')} do
    = semantic_icon 'trash outline'
    = t('helpers.buttons.destroy')

.container-fluid
  .my-3
    .card
      .card-body
        %h4.card-title Вопрос:
        = preserve(markdown(@question.body))
        %h4.card-title Oтвет:
        = render "answers/show/#{@question.code}", answer: @question.code == 'reg_open' ? "/#{@question.answer.body[0]}/"[1..-2] : @question.answer.body, answer_variants: @question.r_answers