edu_test/config/routes.rb
Rails.application.routes.draw do
  resources :question_types, only: :index
  resources :sections
  resources :themes, except: :index

  resources :scenarios do
    member do
      get :test_sessions
    end
  end

  resources :questions, except: :index do
    collection do
      get 'add_answer'
    end
  end

  resources :test_sessions, only: [:show, :index, :new, :create] do
    collection do
      post 'pass'
      post 'pass_part'
    end
  end

  resources :users, only: [:index] do
    collection do
      get :edit_current_user
      patch :update_current_user
      get :reset_current_user
    end
    member do
      get :test_sessions
    end
  end

  namespace :api do
    resources :users
  end

  get 'console', to: 'console#index'

  root 'application#index'
  get '*any', to: 'application#index'
end

edu_test/app/models/theme.rb
class Theme < ApplicationRecord

  belongs_to :section
  has_many :scenario_themes
  has_many :scenarios, through: :scenario_themes
  has_many :questions, dependent: :destroy

  before_destroy :check_assocs

  validates :name, presence: true

  delegate :name, to: :section, prefix: true

  accepts_nested_attributes_for :questions, reject_if: true

  def questions_count
    questions.count
  end

  private

  def check_assocs
    scenarios.blank? && questions.can_destroy?
  end

end

edu_test/app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :admin_user, except: [:index, :show]
  before_action :tutor_user, only: [:index, :show]
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  def show
    @questions = @theme.questions.page(params[:page]).per(10)
    p "Questions: #{@questions.inspect}"
  end

  # GET /themes/new
  def new
    @theme = Theme.new(section_id: params[:section_id])
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to section_path(@theme.section), notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to section_path(@theme.section), notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_theme
    @theme = Theme.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def theme_params
    params.require(:theme).permit(:name, :user_id, :section_id)
  end

end

edu_test/app/helpers/themes_helper.rb
module ThemesHelper
end

edu_test/app/views/themes/_form.html.haml
= bootstrap_form_for @theme do |f|
  - if @theme.errors.any?
    #error_explanation
      %h2= "#{pluralize(@theme.errors.count, "error")} prohibited this section from being saved:"
      %ul
        - @theme.errors.full_messages.each do |msg|
          %li= msg

  = f.input :name
  = f.association :section, disabled: true

  .ui.divider
  = f.button :submit, t('simple_form.submit')

edu_test/app/views/themes/edit.html.haml
- content_for :breadcrumb do
  = sections_breadcrumb
  .section= link_to @theme.section_name, @theme.section
  = divider_tag
  .section.active
    = title(:themes, :edit)
    = link_to @theme.name, @theme

.list-group
  %h2.ui.header.dividing=title(:themes, :edit)
  = render 'form'

edu_test/app/views/themes/index.html.haml
%h1 Listing themes

%table
  %thead
    %tr
      %th Name
      %th User
      %th Section
      %th
      %th
      %th

  %tbody
    - @themes.each do |theme|
      %tr
        %td= theme.name
        %td= theme.user
        %td= theme.section
        %td= link_to 'Show', theme
        %td= link_to 'Edit', edit_theme_path(theme)
        %td= link_to 'Destroy', theme, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Theme', new_theme_path

edu_test/app/views/themes/new.html.haml
- content_for :breadcrumb do
  = sections_breadcrumb
  .section= link_to @theme.section_name, @theme.section
  = divider_tag
  .section.active= title(:themes, :new)

.ui.segment
  %h2.ui.header.dividing=title(:themes, :new)
  = render 'form'

edu_test/app/views/themes/show.html.haml
- content_for :breadcrumb do
  %span.breadcrumb-item= sections_breadcrumb
  %span.breadcrumb-item= link_to @theme.section_name, @theme.section
  %span.breadcrumb-item.active= @theme.name


-#.ui.buttons.floated.right.floated
  = link_to new_question_path(theme_id: @theme.id), class: 'button blue ui icon' do
    = semantic_icon 'plus'
    = t('helpers.buttons.create')
    = t('helpers.models.question.genetive')
  = link_to edit_theme_path(@theme), class: 'button orange ui icon right floated' do
    = semantic_icon 'pencil'
    = t('helpers.buttons.edit')
  = link_to theme_path(@theme), class: 'button red ui icon right floated', data: {method: :delete, confirm: t('helpers.sure')} do
    = semantic_icon 'trash outline'
    = t('helpers.buttons.destroy')

.container-fluid
  .my-3
    %h2= @theme.name
    %h4 Вопросы темы
    %nav.pagination.justify-content-center
      = paginate @questions
    .list-group
      -@questions.each do |question|
        = link_to preserve(markdown(question.body)), question
    %nav.mt-2.pagination.justify-content-center
      = paginate @questions