edu_test/config/routes.rb
Rails.application.routes.draw do
  resources :question_types, only: :index
  resources :sections
  resources :themes, except: :index

  resources :scenarios do
    member do
      get :test_sessions
    end
  end

  resources :questions, except: :index do
    collection do
      get 'add_answer'
    end
  end

  resources :test_sessions, only: [:show, :index, :new, :create] do
    collection do
      post 'pass'
      post 'pass_part'
    end
  end

  resources :users, only: [:index] do
    collection do
      get :edit_current_user
      patch :update_current_user
      get :reset_current_user
    end
    member do
      get :test_sessions
    end
  end

  namespace :api do
    resources :users
  end

  get 'console', to: 'console#index'

  root 'application#index'
  get '*any', to: 'application#index'
end

edu_test/app/controllers/question_types_controller.rb
class QuestionTypesController < ApplicationController
  before_action :admin_user
  # before_action :set_question_type, only: [:show, :edit, :update, :destroy]
  # GET /question_types
  # GET /question_types.json
  def index
    @question_types = QuestionType.all
  end

  # In routes.rb onli index action
  # GET /question_types/1
  # GET /question_types/1.json
  # def show
  # end
  #
  # # GET /question_types/new
  # def new
  #   @question_type = QuestionType.new
  # end
  #
  # # GET /question_types/1/edit
  # def edit
  # end
  #
  # # POST /question_types
  # # POST /question_types.json
  # def create
  #   @question_type = QuestionType.new(question_type_params)
  #
  #   respond_to do |format|
  #     if @question_type.save
  #       format.html { redirect_to @question_type, notice: 'Question type was successfully created.' }
  #       format.json { render :show, status: :created, location: @question_type }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @question_type.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # PATCH/PUT /question_types/1
  # # PATCH/PUT /question_types/1.json
  # def update
  #   respond_to do |format|
  #     if @question_type.update(question_type_params)
  #       format.html { redirect_to @question_type, notice: 'Question type was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @question_type }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @question_type.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /question_types/1
  # # DELETE /question_types/1.json
  # def destroy
  #   @question_type.destroy
  #   respond_to do |format|
  #     format.html { redirect_to question_types_url, notice: 'Question type was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  # def set_question_type
  #   @question_type = QuestionType.find(params[:id])
  # end
  #
  # # Never trust parameters from the scary internet, only allow the white list through.
  # def question_type_params
  #   params.require(:question_type).permit(:name, :klass)
  # end
end

edu_test/app/helpers/question_types_helper.rb
module QuestionTypesHelper
end

edu_test/app/views/question_types/_form.html.haml
= form_for @question_type do |f|
  - if @question_type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question_type.errors.count, "error")} prohibited this question_type from being saved:"
      %ul
        - @question_type.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :klass
    = f.text_field :klass
  .actions
    = f.submit 'Save'

edu_test/app/views/question_types/edit.html.haml
%h1 Editing question_type

= render 'form'

= link_to 'Show', @question_type
\|
= link_to 'Back', question_types_path

edu_test/app/views/question_types/index.html.haml
%h1 Listing question_types

%table
  %thead
    %tr
      %th Name
      %th Klass
      %th
      %th
      %th

  %tbody
    - @question_types.each do |question_type|
      %tr
        %td= question_type.name
        %td= question_type.klass
        %td= link_to 'Show', question_type
        %td= link_to 'Edit', edit_question_type_path(question_type)
        %td= link_to 'Destroy', question_type, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Question type', new_question_type_path

edu_test/app/views/question_types/new.html.haml
%h1 New question_type

= render 'form'

= link_to 'Back', question_types_path

edu_test/app/views/question_types/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @question_type.name
%p
  %b Klass:
  = @question_type.klass

= link_to 'Edit', edit_question_type_path(@question_type)
\|
= link_to 'Back', question_types_path